version: '3.9'

services:
  postgres:
    image: postgres:16.3
    container_name: postgres1
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=casbin
    networks:
      - ntwork
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db-data:/api-gateway/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "22181:2181"
    networks:
      - ntwork
    healthcheck:
      test: ["CMD", "echo", "ruok | nc 127.0.0.1 2181 | grep imok"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    networks:
      - ntwork
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api:
    container_name: ecommerce-apigateway
    build: .
    depends_on:
      postgres:
        condition: service_started
    networks:
      - ntwork
    ports:
      - "8080:8080"

networks:
  ntwork:
    external: true
    name: onenet

volumes:
  db-data:
